version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123456
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
    container_name: my-nextjs
    restart: always
    depends_on:
      - postgres
    expose:
      - "3000"
    environment:
      DATABASE_URL: "postgresql://ecommerce:admin123456@ecommerce.c6tu88k8apyb.us-east-1.rds.amazonaws.com:5432/ecommerce?schema=public&sslmode=require"

  admin:
    build:
      context: ../e-commerce_admin
    container_name: my-admin
    restart: always
    depends_on:
      - postgres
    expose:
      - "3001"
    environment:
      DATABASE_URL: "postgresql://ecommerce:admin123456@ecommerce.c6tu88k8apyb.us-east-1.rds.amazonaws.com:5432/ecommerce?schema=public&sslmode=require"

  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    depends_on:
      - nextjs
      - admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx

volumes:
  pgdata:
